services:
  - type: web
    name: telemetry-backend
    env: node
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production